297 style resource pages
neontribe/sea-map pull request #37
Opened 2020-07-03 15:02 UTC by Nikomus

Trello card: https://trello.com/c/h4fXlidL/297-add-basic-styles-to-help-self-resource-pages

## Description

- Styled resource pages

![image](https://user-images.githubusercontent.com/32434620/86480777-8f6f0700-bd46-11ea-939f-3f45676b915b.png)

@neontribe/sea-map

2020-07-03 15:06 UTC, Nikomus commented on src/Page/Definition.elm
> +quoteStyles : List Style
I'm trying to be consistent with naming `xStyles` for List Style as a hint it's a list of them, not one.

2020-07-03 15:07 UTC, katjam commented on src/Page/HelpSelfSingle.elm
> +    ul [ css [] ]
Do you want to keep this?

2020-07-03 15:11 UTC, katjam reviewed
Couple of minor questions.

2020-07-03 15:11 UTC, katjam commented on src/Page/HelpSelfSingle.elm
> +    List.map (\quoteKey -> p [ css quoteStyles ] [ text (t quoteKey) ]) quoteKeys
blockquote or p?

2020-07-03 16:13 UTC, katjam requested changes

2020-07-03 16:13 UTC, katjam commented on src/Page/HelpSelfSingle.elm
> +    [ blockquote [] ([] ++ renderQuotes resource.quotes)
I think the blockquote needs to be around each one since they are not same person.

2020-07-06 08:54 UTC, katjam approved these changes
Blockquote styling still little confusing - but happy to go with this! :rabbit:

2020-07-06 09:02 UTC, merged